language: csharp
solution: Searchlight.sln
install:
  - nuget restore Searchlight.sln
  - nuget install NUnit -Version 3.6.0 -OutputDirectory nunit
  - nuget install NUnit.Console -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug Searchlight.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./Searchlight.Tests/bin/Debug/netcoreapp1.0/Searchlight.Tests.dll
after_success:
  - echo "Branch is $TRAVIS_BRANCH"
  - echo "Pull Request is $TRAVIS_PULL_REQUEST_BRANCH"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then echo "I would publish to nuget here"; fi
