language: csharp
solution: Searchlight.sln
install:
script:
  - dotnet build Searchlight.sln
  - dotnet test Searchlight.sln
after_success:
  - echo "Branch is $TRAVIS_BRANCH"
  - echo "Pull Request is $TRAVIS_PULL_REQUEST_BRANCH"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then echo "I would publish to nuget here"; fi
